apiVersion: v2
name: loki-stack
description: Observability stack - Loki for logs, Grafana for visualization, Prometheus for metrics, and Grafana Alloy for log collection (alternative to deprecated Promtail) [DOCS => https://rishang.github.io/helm-charts/loki-stack/introduction]
type: application
version: 1.0.2
appVersion: "1.0.2"
icon: https://rishang.github.io/helm-charts/img/loki-stack-icon.png

dependencies:
  - name: loki
    version: "7.0.0"
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled

  - name: rustfs
    version: "0.1.0"
    repository: https://charts.rustfs.com
    condition: rustfs.enabled

  - name: alloy
    version: "1.8.1"
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled

  - name: kube-prometheus-stack
    version: "84.5.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled

maintainers:
  - name: loki-stack-maintainer
    email: rishangbhavsarcs@gmail.com
